export default {
  name: 'Vue SFC - within condition block in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ message }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { isLoggedIn: false };',
    '  },',
    '  methods: {',
    '    checkAuth() {',
    '      if (this.isLoggedIn) {',
    '        console.log("Authenticated");',
    '      }',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'this.isLoggedIn',
  expectedLine: 12,
};
