export default {
  name: 'Vue SFC - dual scripts with arrow function in regular script needing transformation',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ numbers }}</div>',
    '</template>',
    '',
    '<!-- Regular script: Options API -->',
    '<script lang="ts">',
    'export default {',
    '  data() {',
    '    const list = [1, 2, 3, 4, 5];',
    '    const doubled = list.map(num => num * 2);',
    '',
    '    return { doubled };',
    '  },',
    '  computed: {',
    '    numbers() {',
    "      return this.doubled.join(', ');",
    '    }',
    '  }',
    '};',
    '</script>',
    '',
    '<!-- Setup script: Composition API -->',
    '<script setup lang="ts">',
    "import { ref } from 'vue';",
    '',
    "const message = ref('Hello from setup');",
    '</script>',
    '',
    '<style scoped>',
    'div { padding: 1rem; }',
    '</style>',
  ],
  selectionLine: 9,
  variableName: 'num',
};
