export default {
  name: 'Vue SFC - ternary expression in computed',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ status }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { isActive: true };',
    '  },',
    '  computed: {',
    '    status() {',
    '      const message = this.isActive ? "Active" : "Inactive";',
    '      return message;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'message',
  expectedLine: 12,
};
