export default {
  name: 'Vue SFC - raw property access in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ length }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { items: [1, 2, 3, 4, 5] };',
    '  },',
    '  methods: {',
    '    getLength() {',
    '      const person = {',
    '        name: "John",',
    '        age: 30,',
    '      };',
    '      return this.items.length;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 12,
  selectedText: 'name',
  deepObjectPath: 'person.name',
};
