export default {
  name: 'Vue SFC - property access assignment in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ userName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { user: { name: "Alice", profile: { age: 25 } } };',
    '  },',
    '  methods: {',
    '    getUserName() {',
    '      const userName = this.user.name;',
    '      return userName;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'userName',
};
