export default {
  name: 'Vue SFC - template string in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ message }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { name: "John", age: 25 };',
    '  },',
    '  methods: {',
    '    getMessage() {',
    '      const message = `Name: ${this.name}, Age: ${this.age}`;',
    '      return message;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'message',
  expectedLine: 12,
};
