/**
 * Global state keys used throughout the extension
 * Centralized to avoid hardcoding strings and prevent typos
 */
export enum GlobalStateKey {
  // User lifecycle tracking
  IS_NEW_USER = 'IS_NEW_USER',
  EXTENSION_VERSION_HISTORY = 'EXTENSION_VERSION_HISTORY',

  // Release notification tracking
  IS_NOTIFICATION_SHOWN_PREFIX = 'IS_NOTIFICATION_SHOWN_',
  HAS_SHOWN_RELEASE_WEBVIEW = 'HAS_SHOWN_RELEASE_WEBVIEW_',
  HAS_SHOWN_RELEASE_NOTIFICATION = 'HAS_SHOWN_RELEASE_NOTIFICATION_',

  // Pro bundle management
  LICENSE_KEY = 'license-key',
  PRO_BUNDLE = 'pro-bundle',
  PRO_BUNDLE_VERSION = 'version',

  // User journey tracking
  COMMAND_USAGE_COUNT = 'COMMAND_USAGE_COUNT',
  LAST_INSERTION_DATE = 'LAST_INSERTION_DATE',
  STREAK_COUNT = 'STREAK_COUNT',
  HAS_SHOWN_MULTI_FILE_LOGS_NOTIFICATION = 'HAS_SHOWN_MULTI_FILE_LOGS_NOTIFICATION',
  HAS_SHOWN_TEN_COMMANDS_MILESTONE_NOTIFICATION = 'HAS_SHOWN_TEN_COMMANDS_MILESTONE_NOTIFICATION',
  HAS_SHOWN_TEN_INSERTS_MILESTONE_NOTIFICATION = 'HAS_SHOWN_TEN_INSERTS_MILESTONE_NOTIFICATION',
  HAS_SHOWN_TWENTY_INSERTS_MILESTONE_NOTIFICATION = 'HAS_SHOWN_TWENTY_INSERTS_MILESTONE_NOTIFICATION',
  HAS_SHOWN_FIFTY_INSERTS_MILESTONE_NOTIFICATION = 'HAS_SHOWN_FIFTY_INSERTS_MILESTONE_NOTIFICATION',
  HAS_SHOWN_HUNDRED_INSERTS_MILESTONE_NOTIFICATION = 'HAS_SHOWN_HUNDRED_INSERTS_MILESTONE_NOTIFICATION',
  PANEL_OPENING_COUNT = 'PANEL_OPENING_COUNT',
  HAS_SUBSCRIBED_TO_NEWSLETTER = 'HAS_SUBSCRIBED_TO_NEWSLETTER',
  HAS_SHOWN_TWENTY_FIVE_PANEL_OPENINGS_NOTIFICATION = 'HAS_SHOWN_TWENTY_FIVE_PANEL_OPENINGS_NOTIFICATION', // Legacy name - now used for 15 openings milestone
  LOG_MANAGEMENT_COMMAND_USAGE_COUNT = 'LOG_MANAGEMENT_COMMAND_USAGE_COUNT',
  HAS_SHOWN_FIVE_LOG_MANAGEMENT_COMMANDS_NOTIFICATION = 'HAS_SHOWN_FIVE_LOG_MANAGEMENT_COMMANDS_NOTIFICATION',

  // Individual command type tracking
  COMMENT_COMMAND_USAGE_COUNT = 'COMMENT_COMMAND_USAGE_COUNT',
  UNCOMMENT_COMMAND_USAGE_COUNT = 'UNCOMMENT_COMMAND_USAGE_COUNT',
  CORRECTION_COMMAND_USAGE_COUNT = 'CORRECTION_COMMAND_USAGE_COUNT',
  DELETE_COMMAND_USAGE_COUNT = 'DELETE_COMMAND_USAGE_COUNT',
  HAS_SHOWN_FIVE_COMMENTS_COMMANDS_NOTIFICATION = 'HAS_SHOWN_FIVE_COMMENTS_COMMANDS_NOTIFICATION',
  HAS_SHOWN_FIVE_UNCOMMENTS_COMMANDS_NOTIFICATION = 'HAS_SHOWN_FIVE_UNCOMMENTS_COMMANDS_NOTIFICATION',
  HAS_SHOWN_FIVE_CORRECTIONS_COMMANDS_NOTIFICATION = 'HAS_SHOWN_FIVE_CORRECTIONS_COMMANDS_NOTIFICATION',
  HAS_SHOWN_FIVE_DELETE_COMMANDS_NOTIFICATION = 'HAS_SHOWN_FIVE_DELETE_COMMANDS_NOTIFICATION',

  // Pending notifications (scheduled for next activation)
  PENDING_TEN_INSERTS_NOTIFICATION = 'PENDING_TEN_INSERTS_NOTIFICATION',
  PENDING_PHP_WORKSPACE_NOTIFICATION = 'PENDING_PHP_WORKSPACE_NOTIFICATION',

  // Workspace analysis notifications
  HAS_SHOWN_WORKSPACE_LOG_THRESHOLD_NOTIFICATION = 'HAS_SHOWN_WORKSPACE_LOG_THRESHOLD_NOTIFICATION',
  HAS_SHOWN_WORKSPACE_COMMENTED_LOGS_NOTIFICATION = 'HAS_SHOWN_WORKSPACE_COMMENTED_LOGS_NOTIFICATION',
  HAS_SHOWN_WORKSPACE_DUPLICATE_LOGS_NOTIFICATION = 'HAS_SHOWN_WORKSPACE_DUPLICATE_LOGS_NOTIFICATION',
  HAS_SHOWN_WORKSPACE_HOT_FOLDER_NOTIFICATION = 'HAS_SHOWN_WORKSPACE_HOT_FOLDER_NOTIFICATION',

  // PHP workspace detection
  HAS_SHOWN_PHP_WORKSPACE_NOTIFICATION = 'HAS_SHOWN_PHP_WORKSPACE_NOTIFICATION',

  // Workspace log analytics
  WORKSPACE_LOG_METADATA = 'WORKSPACE_LOG_METADATA',

  // Messy file detection (JS/TS and PHP)
  HAS_SHOWN_JS_MESSY_FILE_NOTIFICATION = 'HAS_SHOWN_JS_MESSY_FILE_NOTIFICATION',
  HAS_SHOWN_PHP_MESSY_FILE_NOTIFICATION = 'HAS_SHOWN_PHP_MESSY_FILE_NOTIFICATION',

  // Multi-type log detection (JS/TS and PHP)
  HAS_SHOWN_JS_MULTI_LOG_TYPES_NOTIFICATION = 'HAS_SHOWN_JS_MULTI_LOG_TYPES_NOTIFICATION',
  HAS_SHOWN_PHP_MULTI_LOG_TYPES_NOTIFICATION = 'HAS_SHOWN_PHP_MULTI_LOG_TYPES_NOTIFICATION',

  // Weekend Turbo Sundays notification (one-time)
  HAS_SHOWN_WEEKEND_TURBO_SUNDAYS_NOTIFICATION = 'HAS_SHOWN_WEEKEND_TURBO_SUNDAYS_NOTIFICATION',

  // User activity status tracking
  USER_ACTIVITY_STATUS = 'USER_ACTIVITY_STATUS',
  ACTIVITY_CHECK_START_DATE = 'ACTIVITY_CHECK_START_DATE',
  HAS_SHOWN_INACTIVE_MANUAL_LOG_NOTIFICATION = 'HAS_SHOWN_INACTIVE_MANUAL_LOG_NOTIFICATION',
  HAS_SHOWN_INACTIVE_TWO_WEEKS_RETURN_NOTIFICATION = 'HAS_SHOWN_INACTIVE_TWO_WEEKS_RETURN_NOTIFICATION',
  HAS_SHOWN_INACTIVE_FOUR_WEEKS_SURVEY_NOTIFICATION = 'HAS_SHOWN_INACTIVE_FOUR_WEEKS_SURVEY_NOTIFICATION',
  HAS_SHOWN_ACTIVATION_DAY_THREE_NOTIFICATION = 'HAS_SHOWN_ACTIVATION_DAY_THREE_NOTIFICATION',
  HAS_SHOWN_ACTIVATION_DAY_SEVEN_NOTIFICATION = 'HAS_SHOWN_ACTIVATION_DAY_SEVEN_NOTIFICATION',

  // Git commit detection
  HAS_SHOWN_COMMIT_WITH_LOGS_NOTIFICATION = 'HAS_SHOWN_COMMIT_WITH_LOGS_NOTIFICATION',

  // Custom logging library detection
  HAS_SHOWN_CUSTOM_LOG_LIBRARY_NOTIFICATION = 'HAS_SHOWN_CUSTOM_LOG_LIBRARY_NOTIFICATION',
  HAS_SHOWN_LOG_LIBRARY_INSTALLED_NOTIFICATION = 'HAS_SHOWN_LOG_LIBRARY_INSTALLED_NOTIFICATION',

  // Logs in test file detection
  HAS_SHOWN_LOGS_IN_TEST_FILE_NOTIFICATION = 'HAS_SHOWN_LOGS_IN_TEST_FILE_NOTIFICATION',
}
