export default {
  name: 'Vue SFC - property method call in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ upperName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { name: "john" };',
    '  },',
    '  methods: {',
    '    formatName() {',
    '      const upperName = this.name.toUpperCase();',
    '      return upperName;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'upperName',
  expectedLine: 12,
};
