export default {
  name: 'Vue SFC - named function assignment in computed property',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ fullName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { firstName: "John", lastName: "Doe" };',
    '  },',
    '  computed: {',
    '    fullName() {',
    '      const formatName = function(first, last) {',
    '        return `${first} ${last}`;',
    '      };',
    '      return formatName(this.firstName, this.lastName);',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'formatName',
};
