export default {
  name: 'Vue SFC - function assignment in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ result }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  methods: {',
    '    calculate() {',
    '      const multiply = (a, b) => a * b;',
    '      const result = multiply(5, 3);',
    '      return result;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 8,
  selectedVar: 'multiply',
  expectedLine: 9,
};
