export default {
  name: 'Vue SFC - primitive assignment in watch',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ count }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { count: 0 };',
    '  },',
    '  watch: {',
    '    count(newVal) {',
    '      const value = 42;',
    '      console.log(value);',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'value',
};
