export default {
  name: 'Vue SFC - object function call assignment in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ result }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { result: null };',
    '  },',
    '  methods: {',
    '    calculate() {',
    '      const result = Math.random();',
    '      this.result = result;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'result',
};
