export default {
  name: 'Simple Vue 3 component with Composition API and template',
  sourceCode: [
    '// File: simple-vue.ts',
    "import { ref, computed, defineComponent } from 'vue';",
    '',
    'export default defineComponent({',
    "  name: 'SimpleCounter',",
    '  props: {',
    '    initialCount: {',
    '      type: Number,',
    '      default: 0,',
    '    },',
    '  },',
    '  template: `',
    '    <div class="counter">',
    '      <h2>Counter: {{ count }}</h2>',
    '      <p>Doubled: {{ doubled }}</p>',
    '      <div class="buttons">',
    '        <button @click="decrement" :disabled="count <= 0">-</button>',
    '        <button @click="increment">+</button>',
    '      </div>',
    '      <small v-if="count === 0">Click + to start counting</small>',
    '      <small v-else-if="count > 10">Wow, that\'s a lot!</small>',
    '    </div>',
    '  `,',
    '  styles: [`',
    '    .counter {',
    '      padding: 20px;',
    '      border: 1px solid #ccc;',
    '      border-radius: 8px;',
    '      max-width: 300px;',
    '      margin: 0 auto;',
    '    }',
    '    .counter h2 {',
    '      margin: 0 0 10px;',
    '      color: #333;',
    '    }',
    '    .buttons {',
    '      display: flex;',
    '      gap: 10px;',
    '      margin: 15px 0;',
    '    }',
    '    .buttons button {',
    '      flex: 1;',
    '      padding: 10px;',
    '      font-size: 18px;',
    '      border-radius: 4px;',
    '      border: 1px solid #007bff;',
    '      background: #007bff;',
    '      color: white;',
    '      cursor: pointer;',
    '    }',
    '    .buttons button:disabled {',
    '      opacity: 0.5;',
    '      cursor: not-allowed;',
    '    }',
    '    small {',
    '      display: block;',
    '      margin-top: 10px;',
    '      color: #666;',
    '    }',
    '  `],',
    '  setup(props, { emit }) {',
    '    const count = ref(props.initialCount);',
    '    const doubled = computed(() => count.value * 2);',
    '',
    '    const increment = () => {',
    '      count.value++;',
    "      emit('update', count.value);",
    '    };',
    '',
    '    const decrement = () => {',
    '      count.value--;',
    "      emit('update', count.value);",
    '    };',
    '',
    '    return {',
    '      count,',
    '      doubled,',
    '      increment,',
    '      decrement,',
    '    };',
    '  },',
    '});',
  ],
};
