export default {
  name: 'React TypeScript component with hooks',
  fileExtension: '.tsx',
  sourceCode: [
    '// File: SimpleTodoList.tsx',
    'import React, { useEffect, useMemo, useState } from "react";',
    '',
    'type SimpleTodoListProps = {',
    '  initialItems?: string[];',
    '  title?: string;',
    '};',
    '',
    'export default function SimpleTodoList({ initialItems = [], title = "Todos" }: SimpleTodoListProps) {',
    '  const [items, setItems] = useState<string[]>(initialItems);',
    '  const [q, setQ] = useState("");',
    '',
    '  // tiny derived value to exercise closures & memo (easy for parser)',
    '  const visible = useMemo(() => {',
    '    const needle = q.trim().toLowerCase();',
    '    return needle ? items.filter((t) => t.toLowerCase().includes(needle)) : items;',
    '  }, [items, q]);',
    '',
    '  // no-op effect (keeps it realistic but simple)',
    '  useEffect(() => {',
    '    if (items.length > 50) {',
    '      // eslint-disable-next-line no-console',
    '      console.log("Large list");',
    '    }',
    '  }, [items.length]);',
    '',
    '  function addItem() {',
    '    const v = q.trim();',
    '    if (!v) return;',
    '    setItems((arr) => arr.concat(v));',
    '    setQ("");',
    '  }',
    '',
    '  function remove(index: number) {',
    '    setItems((arr) => arr.filter((_, i) => i !== index));',
    '  }',
    '',
    '  return (',
    '    <section>',
    '      <h2>{title}</h2>',
    '',
    '      <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>',
    '        <input',
    '          value={q}',
    '          onChange={(e) => setQ(e.target.value)}',
    '          placeholder="Add or search…"',
    '        />',
    '        <button onClick={addItem}>Add</button>',
    '      </div>',
    '',
    '      <ul>',
    '        {visible.map((t, i) => (',
    '          <li key={i} style={{ display: "flex", alignItems: "center", gap: 8 }}>',
    '            <span>{t}</span>',
    '            <button onClick={() => remove(i)}>✕</button>',
    '          </li>',
    '        ))}',
    '      </ul>',
    '',
    '      {!visible.length && <small style={{ opacity: 0.7 }}>No items</small>}',
    '    </section>',
    '  );',
    '}',
  ],
};
