export default {
  name: 'Astro - TypeScript frontmatter with imports',
  fileExtension: '.astro',
  sourceCode: [
    '---',
    'import { getCollection } from "astro:content";',
    'import type { CollectionEntry } from "astro:content";',
    '',
    'interface Props {',
    '  title: string;',
    '}',
    '',
    'const { title } = Astro.props;',
    'const posts: CollectionEntry<"blog">[] = await getCollection("blog");',
    '---',
    '',
    '<html lang="en">',
    '  <head>',
    '    <title>{title}</title>',
    '  </head>',
    '  <body>',
    '    <h1>Blog Posts</h1>',
    '    {posts.map(post => (',
    '      <article>',
    '        <h2>{post.data.title}</h2>',
    '      </article>',
    '    ))}',
    '  </body>',
    '</html>',
  ],
  selectionLine: 9, // Line where "const posts" is - 0-based
};
