export default {
  name: 'JSX with complex expressions in .js file',
  sourceCode: [
    "import React, { useState } from 'react';",
    '',
    'function Counter() {',
    '  const [count, setCount] = useState(0);',
    '  const handleClick = () => setCount(count + 1);',
    '  ',
    '  return (',
    '    <div>',
    '      <button onClick={handleClick}>',
    '        Count: {count}',
    '      </button>',
    '      {count > 5 && <p>High count!</p>}',
    '    </div>',
    '  );',
    '}',
  ],
  fileExtension: '.js',
  selectionLine: 4,
};
