export default {
  name: 'JSX with array methods and callbacks in .js file',
  sourceCode: [
    "import React from 'react';",
    '',
    'function UserList({ users }) {',
    '  const activeUsers = users.filter(u => u.active);',
    '  const sortedUsers = activeUsers.sort((a, b) => a.name.localeCompare(b.name));',
    '  ',
    '  return (',
    '    <ul className="user-list">',
    '      {sortedUsers.map(user => (',
    '        <li key={user.id}>',
    '          <span>{user.name}</span>',
    '          <span>{user.email}</span>',
    '        </li>',
    '      ))}',
    '    </ul>',
    '  );',
    '}',
  ],
  fileExtension: '.js',
  selectionLine: 4,
};
