export default {
  name: 'JSX with hooks and useEffect in .js file',
  sourceCode: [
    "import React, { useState, useEffect } from 'react';",
    '',
    'function DataFetcher({ url }) {',
    '  const [data, setData] = useState(null);',
    '  const [loading, setLoading] = useState(true);',
    '  ',
    '  useEffect(() => {',
    '    fetch(url)',
    '      .then(res => res.json())',
    '      .then(data => {',
    '        setData(data);',
    '        setLoading(false);',
    '      });',
    '  }, [url]);',
    '  ',
    '  return (',
    '    <div>',
    '      {loading ? <p>Loading...</p> : <pre>{JSON.stringify(data, null, 2)}</pre>}',
    '    </div>',
    '  );',
    '}',
  ],
  fileExtension: '.js',
  selectionLine: 3,
};
