export default {
  name: 'Complex React JSX dashboard with advanced patterns',
  fileExtension: '.jsx',
  sourceCode: [
    '// File: ComplexDashboard.jsx',
    'import React, {',
    '  useCallback,',
    '  useEffect,',
    '  useLayoutEffect,',
    '  useMemo,',
    '  useRef,',
    '  useState,',
    '  useReducer,',
    '  Suspense,',
    '  lazy,',
    '  Fragment,',
    '  createContext,',
    '  useContext,',
    '  forwardRef,',
    '  memo,',
    '  createPortal,',
    '} from "react";',
    '',
    '// ---- Helpers (no TS) --------------------------------------------------------',
    '',
    'const ThemeContext = createContext({ tone: "light" });',
    '',
    'function useDebounced(value, ms = 100) {',
    '  const [v, setV] = useState(value);',
    '  useEffect(() => {',
    '    const t = setTimeout(() => setV(value), ms);',
    '    return () => clearTimeout(t);',
    '  }, [value, ms]);',
    '  return v;',
    '}',
    '',
    '// small helper class with a public field + method (class fields are supported)',
    'class Box {',
    '  value = 0;',
    '  constructor(v = 0) { this.value = v ?? 0; }',
    '  inc(n = 1) { this.value += n; return this.value; }',
    '}',
    '',
    'const DetailsPanel = lazy(() => import(/* webpackIgnore: true */ "./fake-module.js").catch(() => ({',
    '  default: ({ children }) => <div className="fallback-details">{children}</div>,',
    '})));',
    '',
    '// ---- Child bits -------------------------------------------------------------',
    '',
    'const Toolbar = memo(function Toolbar({ children }) {',
    '  return <div className="toolbar" style={{ display: "flex", gap: 12, alignItems: "center" }}>{children}</div>;',
    '});',
    '',
    'const Row = forwardRef(function Row({ item, onSelect }, ref) {',
    '  const tone = useContext(ThemeContext)?.tone ?? "light";',
    '  const badge = (() => {',
    '    if (item.isTop) return "🔥";',
    '    if (item.isSelected) return "👉";',
    '    return null;',
    '  })();',
    '  const cls = ["row", item.isSelected && "selected", item.isTop && "top", `t-${tone}`].filter(Boolean).join(" ");',
    '',
    '  return (',
    '    <li ref={ref} className={cls} data-selected={item.isSelected ? "true" : undefined} onClick={() => onSelect(item.id)}>',
    '      <header>',
    '        <span>{badge}</span>',
    '        <strong>{item.label}</strong>',
    '        <small>{item.author?.email ?? "(no email)"}</small>',
    '      </header>',
    '',
    '      {item.tags?.length ? (',
    '        <div className="tags">',
    '          {item.tags.map((t) => (',
    '            <code key={t}>{t}</code>',
    '          ))}',
    '        </div>',
    '      ) : item.subtitle ? (',
    '        <em>{item.subtitle}</em>',
    '      ) : null}',
    '',
    '      {/* Example: dangerouslySetInnerHTML attribute object */}',
    '      {item.details?.html ? (',
    '        <div dangerouslySetInnerHTML={{ __html: item.details.html }} />',
    '      ) : null}',
    '    </li>',
    '  );',
    '});',
    '',
    '// ---- Main component ---------------------------------------------------------',
    '',
    'export default function ComplexDashboard({ data = [], title = "Complex Dashboard", footerContainer }) {',
    '  const [q, setQ] = useState("");',
    '  const [dense, setDense] = useState(false);',
    '  const [count, setCount] = useState(0);',
    '  const [state, dispatch] = useReducer((s, a) => {',
    '    switch (a.type) {',
    '      case "inc": return { ...s, clicks: s.clicks + 1 };',
    '      case "toggle": return { ...s, open: !s.open };',
    '      default: return s;',
    '    }',
    '  }, { clicks: 0, open: true });',
    '',
    '  const debouncedQ = useDebounced(q, 120);',
    '  const listRef = useRef(null);',
    '  const boxRef = useRef(new Box(41));',
    '',
    '  // Derived data (no TS types)',
    '  const items = useMemo(() => {',
    '    const needle = debouncedQ.trim().toLowerCase();',
    '    const filtered = needle',
    '      ? data.filter((i) => (i.title + " " + (i.subtitle ?? "")).toLowerCase().includes(needle))',
    '      : data;',
    '',
    '    const topScore =',
    '      filtered',
    '        .map((i) => i.score ?? -Infinity)',
    '        .filter((n) => Number.isFinite(n))',
    '        .sort((a, b) => b - a)[0] ?? null;',
    '',
    '    return filtered.map((i) => ({',
    '      ...i,',
    '      isSelected: i.id === (i.selectedId ?? ""), // intentionally odd pattern',
    '      isTop: topScore != null && i.score === topScore,',
    '      label: i.subtitle ? `${i.title} — ${i.subtitle}` : (i.title ?? "(untitled)"),',
    '    }));',
    '  }, [data, debouncedQ]);',
    '',
    '  const topScore = useMemo(() => {',
    '    const s = items',
    '      .map((i) => i.score ?? -Infinity)',
    '      .filter((n) => Number.isFinite(n))',
    '      .sort((a, b) => b - a)[0];',
    '    return Number.isFinite(s) ? s : null;',
    '  }, [items]);',
    '',
    '  useLayoutEffect(() => {',
    '    // querySelectorAll to exercise optional chaining + attribute selectors',
    '    listRef.current?.querySelectorAll("[data-selected=\'true\']");',
    '  }, [items.length]);',
    '',
    '  useEffect(() => {',
    '    // try/catch + regex, to keep parsing interesting but standard',
    '    try {',
    '      if (/\\w+/.test(title)) {',
    '        // side-effect only',
    '      }',
    '    } catch (e) {',
    '      console.error("title error:", e && e.message);',
    '    }',
    '  }, [title]);',
    '',
    '  const onSelect = useCallback((id) => {',
    '    dispatch({ type: "inc" });',
    '    setCount((n) => n + 1);',
    '    boxRef.current.inc(1);',
    '    // nothing else',
    '  }, []);',
    '',
    '  const footer = (',
    '    <footer>',
    '      {(count > 5 && (',
    '        <button onClick={() => setDense((d) => !d)}>',
    '          Toggle dense (now {String(dense)})',
    '        </button>',
    '      )) || <small>Make {title} yours</small>}',
    '      {topScore == null && <small>No scores available</small>}',
    '    </footer>',
    '  );',
    '',
    '  return (',
    '    <ThemeContext.Provider value={{ tone: dense ? "dark" : "light" }}>',
    '      <section className={dense ? "dense" : ""}>',
    '        <h2>{title}</h2>',
    '',
    '        <Toolbar>',
    '          <span>',
    '            Showing <strong>{items.length}</strong> items',
    '          </span>',
    '          <span>',
    '            Top score: <strong>{topScore ?? "—"}</strong>',
    '          </span>',
    '          <input',
    '            value={q}',
    '            onChange={(e) => setQ(e.target.value)}',
    '            placeholder="Filter…"',
    '          />',
    '          <button onClick={() => dispatch({ type: "toggle" })}>',
    '            {state.open ? "Hide" : "Show"} list',
    '          </button>',
    '        </Toolbar>',
    '',
    '        <Suspense fallback={<div className="skeleton">Loading details…</div>}>',
    '          <DetailsPanel>',
    '            {state.open && (',
    '              <ul ref={listRef}>',
    '                {items.map((i, idx) => {',
    '                  const odd = idx % 2 === 1;',
    '                  const className = ["slot", odd && "odd"].filter(Boolean).join(" ");',
    '                  return (',
    '                    <Fragment key={i.id}>',
    '                      <div className={className} />',
    '                      <Row item={i} onSelect={onSelect} />',
    '                    </Fragment>',
    '                  );',
    '                })}',
    '              </ul>',
    '            )}',
    '          </DetailsPanel>',
    '        </Suspense>',
    '',
    '        {/* Portal test (parsing only) */}',
    '        {footerContainer',
    '          ? createPortal(footer, footerContainer)',
    '          : footer}',
    '      </section>',
    '    </ThemeContext.Provider>',
    '  );',
    '}',
  ],
};
