export default {
  name: 'Angular component with decorators and template syntax',
  sourceCode: [
    '// File: hello.component.ts  (REAL ANGULAR — will fail on Acorn without decorator support)',
    "import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';",
    '',
    '@Component({',
    "  selector: 'app-hello',",
    '  changeDetection: ChangeDetectionStrategy.OnPush,',
    '  template: `',
    '    <section>',
    '      <h2>Hello, {{ name }}</h2>',
    '      <button (click)="increment()">Clicked {{ count }} times</button>',
    '      <small *ngIf="count === 0">Click the button!</small>',
    '    </section>',
    '  `,',
    '})',
    'export class HelloComponent {',
    "  @Input() name = 'World';",
    '  @Output() changed = new EventEmitter<number>();',
    '',
    '  count = 0;',
    '',
    '  increment(): void {',
    '    this.count++;',
    '    this.changed.emit(this.count);',
    '  }',
    '}',
  ],
};
