export default {
  name: 'Vue SFC - function call assignment in lifecycle hook',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ data }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { data: null };',
    '  },',
    '  mounted() {',
    '    const result = this.fetchData();',
    '    this.data = result;',
    '  },',
    '  methods: {',
    '    fetchData() {',
    '      return "data";',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 10,
  variableName: 'result',
};
