export default {
  name: 'Vue SFC - dual scripts with function call in setup script (ref)',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <section>',
    '    <h2>{{ title }}</h2>',
    '    <p>{{ message }}</p>',
    '    <button @click="increment">Clicked {{ count }} times</button>',
    '  </section>',
    '</template>',
    '',
    '<!-- Regular script: component options / classic logic -->',
    '<script lang="ts">',
    "import type { PropType } from 'vue';",
    '',
    'export default {',
    "  name: 'DualScriptExample',",
    '  props: {',
    '    title: {',
    '      type: String as PropType<string>,',
    "      default: 'Hello from regular <script>',",
    '    },',
    '  },',
    '',
    '  data() {',
    '    // ✅ This is a variable Turbo could log',
    '    const visits = 42;',
    "    console.log('visits:', visits); // ← sample log target",
    '    return { visits };',
    '  },',
    '',
    '  methods: {',
    '    logMount() {',
    "      console.log('Component mounted — regular script method');",
    '    },',
    '  },',
    '',
    '  mounted() {',
    '    this.logMount();',
    '  },',
    '};',
    '</script>',
    '',
    '<!-- Setup script: composition logic / reactive state -->',
    '<script setup lang="ts">',
    "import { ref, onMounted } from 'vue';",
    '',
    "const message = ref('Greetings from <script setup>!');",
    'const count = ref(0);',
    '',
    'function increment() {',
    '  count.value++;',
    "  console.log('Count incremented to', count.value);",
    '}',
    '',
    'onMounted(() => {',
    "  console.log('Setup script mounted — reactive state ready');",
    '});',
    '</script>',
    '',
    '<style scoped>',
    'section {',
    '  padding: 1rem;',
    '  border: 1px solid #ccc;',
    '  border-radius: 8px;',
    '}',
    '</style>',
  ],
  selectionLine: 45,
  variableName: 'count',
};
