// Type definitions
export type {
  AcornNode,
  Literal,
  Identifier,
  ThisExpression,
  MemberExpression,
  VariableDeclarator,
  VariableDeclaration,
  ObjectPattern,
  ArrayPattern,
  Property,
  TemplateLiteral,
  TaggedTemplateExpression,
  ArrayExpression,
  ObjectExpression,
  CallExpression,
  FunctionDeclaration,
  FunctionExpression,
  ArrowFunctionExpression,
  BinaryExpression,
  LogicalExpression,
  ConditionalExpression,
  ReturnStatement,
  BlockStatement,
  ExpressionStatement,
  AssignmentExpression,
  ParenthesizedExpression,
  TSAsExpression,
  TSTypeAssertion,
  AwaitExpression,
  RestElement,
  AssignmentPattern,
  ChainExpression,
  MethodDefinition,
  ClassMethod,
  TSParameterProperty,
} from './types';

// Type guards
export {
  isLiteral,
  isIdentifier,
  isThisExpression,
  isMemberExpression,
  isVariableDeclaration,
  isObjectPattern,
  isArrayPattern,
  isTemplateLiteral,
  isTaggedTemplateExpression,
  isArrayExpression,
  isObjectExpression,
  isCallExpression,
  isFunctionDeclaration,
  isFunctionExpression,
  isArrowFunctionExpression,
  isBinaryExpression,
  isLogicalExpression,
  isConditionalExpression,
  isReturnStatement,
  isBlockStatement,
  isExpressionStatement,
  isAssignmentExpression,
  isParenthesizedExpression,
  isTSAsExpression,
  isTSTypeAssertion,
  isAwaitExpression,
  isRestElement,
  isAssignmentPattern,
  isChainExpression,
  isMethodDefinition,
  isClassMethod,
  isProperty,
  isClassDeclaration,
  isVariableDeclarator,
  isTSParameterProperty,
} from './guards';

// AST walker
export { walk } from './walk';

// Parser
export { parseCode } from './parseCode';
