export default {
  name: 'Vue SFC - array assignment in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ items }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { items: [] };',
    '  },',
    '  methods: {',
    '    loadData() {',
    '      const data = [1, 2, 3];',
    '      this.items = data;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'data',
  expectedLine: 12,
};
