import { LogMessageType } from '@/entities';
import { InsertionEngineCase } from './types';

// Guards for "log before the statement" placements. A log inserted between a
// braceless `if`/`else`/loop head and its body becomes the body and pushes the
// original statement out of it (a throw then runs on every call); a log on a
// line that also holds `else` or a `case 'x':` label is a SyntaxError. Before
// climbs out of both, up to the whole if/else or switch.
export const beforeStatementAnchorCases: InsertionEngineCase[] = [
  {
    name: 'method-call object in a throw under a braceless if is logged before the if',
    fileExtension: '.js',
    lines: [
      'function f(user, errors) {',
      '  if (!user)',
      '    throw errors.notFound(user);',
      '  return user;',
      '}',
    ],
    selectionLine: 2,
    variableName: 'errors',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.PropertyMethodCall,
  },
  {
    name: 'method-call object in a throw under a braceless else is logged before the if',
    fileExtension: '.js',
    lines: [
      'function f(a, errors) {',
      '  if (a) run();',
      '  else',
      '    throw errors.bad(a);',
      '}',
    ],
    selectionLine: 3,
    variableName: 'errors',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.PropertyMethodCall,
  },
  {
    name: 'method-call object in a same-line else throw is logged before the if',
    fileExtension: '.js',
    lines: [
      'function f(a, errors) {',
      '  if (a) run();',
      '  else throw errors.bad(a);',
      '  return a;',
      '}',
    ],
    selectionLine: 2,
    variableName: 'errors',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.PropertyMethodCall,
  },
  {
    name: 'method-call object in a same-line case throw is logged before the switch',
    fileExtension: '.js',
    lines: [
      'function f(a, errors) {',
      '  switch (a) {',
      "    case 'x': throw errors.bad(a);",
      '    default: break;',
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'errors',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.PropertyMethodCall,
  },
  {
    name: 'member in a same-line case throw new Error is logged before the switch',
    fileExtension: '.js',
    lines: [
      'function f(a, user) {',
      '  switch (a) {',
      "    case 'x': throw new Error(user.msg);",
      '    default: break;',
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'user.msg',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.WanderingExpression,
  },
  {
    name: 'key in a same-line else return literal logs its value before the if',
    fileExtension: '.js',
    lines: [
      'function f(user) {',
      '  if (!user) return null;',
      '  else return { id: user.id };',
      '}',
    ],
    selectionLine: 2,
    variableName: 'id',
    expectedLine: 1,
    expectedDeepObjectPath: 'user.id',
  },
  {
    name: 'key in a same-line case return literal logs its value before the switch',
    fileExtension: '.js',
    lines: [
      'function f(a, user) {',
      '  switch (a) {',
      "    case 'x': return { id: user.id };",
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'id',
    expectedLine: 1,
    expectedDeepObjectPath: 'user.id',
  },
  {
    name: 'key in a multi-line literal returned under a braceless if logs before the if',
    fileExtension: '.js',
    lines: [
      'function f(user) {',
      '  if (user)',
      '    return {',
      '      id: user.id,',
      '    };',
      '  return null;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'id',
    expectedLine: 1,
    expectedDeepObjectPath: 'user.id',
  },
  {
    name: 'method-call object in a multi-line call under a braceless if is logged before the if',
    fileExtension: '.js',
    lines: [
      'function f(a, store) {',
      '  if (a)',
      '    render(',
      '      store.getState(),',
      '    );',
      '}',
    ],
    selectionLine: 3,
    variableName: 'store',
    expectedLine: 1,
  },
  {
    name: 'key whose value is a call logs the key name as a string, never an undeclared identifier',
    fileExtension: '.js',
    lines: ['function f() {', '  save({', '    stamp: now(),', '  });', '}'],
    selectionLine: 2,
    variableName: 'stamp',
    expectedLine: 1,
    expectedDeepObjectPath: '"stamp"',
  },
  {
    name: 'key with a multi-line value logs the value joined on one line',
    fileExtension: '.js',
    lines: [
      'function f(a, b) {',
      '  return {',
      '    items: [',
      '      a,',
      '      b,',
      '    ],',
      '  };',
      '}',
    ],
    selectionLine: 2,
    variableName: 'items',
    expectedLine: 1,
    expectedDeepObjectPath: '[ a, b, ]',
  },
  {
    name: 'return in a function body opening on the outer return line is logged before the outer return',
    fileExtension: '.js',
    lines: [
      'function createCallback(value) {',
      '  return function () { return value; };',
      '}',
    ],
    selectionLine: 1,
    variableName: 'value',
    expectedLine: 1,
  },
  {
    name: 'parameter of a function whose brace line ends with a comment is logged inside the body',
    fileExtension: '.js',
    lines: ['function f(a) { // note', '  return a;', '}'],
    selectionLine: 0,
    variableName: 'a',
    expectedLine: 1,
    expectedLogMessageType: LogMessageType.FunctionParameter,
  },
  {
    // No line both keeps the log in the loop variable's scope and stays out of
    // the braceless body: only wrapping the body in braces can do it.
    name: 'condition under a braceless for-of body that reads the loop variable',
    fileExtension: '.js',
    lines: [
      'function f(items) {',
      '  for (const item of items)',
      '    if (item.ok) run(item);',
      '}',
    ],
    selectionLine: 2,
    variableName: 'item.ok',
    expectedLine: 2,
    expectsTransformation: true,
    knownBroken: true,
  },
];
