import { InsertionEngineCase } from './types';

// Selections inside a function nested in a `return` argument (map callbacks in
// JSX, inline handlers, returned closures, effect cleanups) belong to that
// function: they are logged in its scope, never before the outer `return`,
// where the callback bindings are out of scope.
export const callbackInsideReturnCases: InsertionEngineCase[] = [
  {
    name: 'member in a map callback JSX return is logged before the inner return',
    fileExtension: '.tsx',
    lines: [
      'export function Menu({ items, selectedId }: MenuProps) {',
      '  return (',
      '    <ul>',
      '      {items.map((item) => {',
      '        const isSelected = item.id === selectedId;',
      '        return (',
      "          <li key={item.id} className={isSelected ? 'active' : ''}>",
      '            {item.label}',
      '          </li>',
      '        );',
      '      })}',
      '    </ul>',
      '  );',
      '}',
    ],
    selectionLine: 7,
    variableName: 'item.label',
    expectedLine: 5,
  },
  {
    name: 'member in a single-line inner JSX return is logged before that return',
    fileExtension: '.tsx',
    lines: [
      'export function Tags({ tags }: { tags: Tag[] }) {',
      '  return (',
      '    <div>',
      '      {tags.map((tag) => {',
      '        const label = formatTag(tag);',
      '        return <span key={tag.id}>{label}</span>;',
      '      })}',
      '    </div>',
      '  );',
      '}',
    ],
    selectionLine: 5,
    variableName: 'tag.id',
    expectedLine: 5,
  },
  {
    name: 'const inside an inline JSX onClick handler is logged after the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function Toggle({ onToggle }: Props) {',
      '  const [open, setOpen] = useState(false);',
      '  return (',
      '    <button',
      '      type="button"',
      '      onClick={() => {',
      '        const next = !open;',
      '        setOpen(next);',
      '        onToggle?.(next);',
      '      }}',
      '    >',
      '      {open ? "Close" : "Open"}',
      '    </button>',
      '  );',
      '}',
    ],
    selectionLine: 6,
    variableName: 'next',
    expectedLine: 7,
  },
  {
    name: 'assignment inside a useEffect cleanup closure is logged after the assignment',
    fileExtension: '.tsx',
    lines: [
      'export function UserProfile({ userId }: { userId: string }) {',
      '  const [user, setUser] = useState<User | null>(null);',
      '  useEffect(() => {',
      '    let cancelled = false;',
      '    async function load() {',
      '      const response = await fetch(`/api/users/${userId}`);',
      '      const json = await response.json();',
      '      if (!cancelled) setUser(json);',
      '    }',
      '    load();',
      '    return () => {',
      '      cancelled = true;',
      '    };',
      '  }, [userId]);',
      '  if (!user) return <Spinner />;',
      '  return <Avatar src={user.avatarUrl} alt={user.name} />;',
      '}',
    ],
    selectionLine: 11,
    variableName: 'cancelled',
    expectedLine: 12,
  },
  {
    name: 'value in a multi-line dispatch inside a returned async closure is logged before the dispatch',
    fileExtension: '.tsx',
    lines: [
      'export function useLogin() {',
      '  const dispatch = useDispatch();',
      '  return async (credentials: Credentials) => {',
      '    const user = await api.login(credentials);',
      '    dispatch({',
      "      type: 'SET_USER',",
      '      payload: user,',
      '    });',
      '  };',
      '}',
    ],
    selectionLine: 6,
    variableName: 'user',
    expectedLine: 4,
  },
  {
    name: 'member arg in a single-line dispatch inside a returned thunk is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'export function fetchUser(id: string) {',
      '  return async (dispatch: AppDispatch) => {',
      '    const res = await api.get(`/users/${id}`);',
      "    dispatch({ type: 'user/loaded', payload: res.data });",
      '  };',
      '}',
    ],
    selectionLine: 3,
    variableName: 'res.data',
    expectedLine: 4,
  },
  {
    name: 'const inside a handler of an object returned by a hook is logged after the declaration',
    fileExtension: '.ts',
    lines: [
      'export function useDisclosure(initial = false) {',
      '  const [isOpen, setIsOpen] = useState(initial);',
      '  return {',
      '    isOpen,',
      '    toggle: () => {',
      '      const next = !isOpen;',
      '      setIsOpen(next);',
      '    },',
      '  };',
      '}',
    ],
    selectionLine: 5,
    variableName: 'next',
    expectedLine: 6,
  },
  {
    name: 'call arg inside an if inside a JSX onClick handler is logged after the statement',
    fileExtension: '.tsx',
    lines: [
      'export function DeleteButton({ id, onDelete }: Props) {',
      '  return (',
      '    <button',
      '      onClick={() => {',
      "        if (window.confirm('Delete this item?')) {",
      '          onDelete(id);',
      '        }',
      '      }}',
      '    >',
      '      Delete',
      '    </button>',
      '  );',
      '}',
    ],
    selectionLine: 5,
    variableName: 'id',
    expectedLine: 6,
  },
  {
    name: 'member in the inner return of a render prop is logged before that return',
    fileExtension: '.tsx',
    lines: [
      'export function Routes() {',
      '  return (',
      '    <Route',
      '      path="/users/:id"',
      '      render={(routeProps) => {',
      '        const userId = routeProps.match.params.id;',
      '        return <UserPage id={userId} />;',
      '      }}',
      '    />',
      '  );',
      '}',
    ],
    selectionLine: 6,
    variableName: 'userId',
    expectedLine: 6,
  },
  {
    name: 'statement inside a callback nested in a returned Promise is logged after the statement',
    fileExtension: '.js',
    lines: [
      'function readConfig(path) {',
      '  return new Promise((resolve, reject) => {',
      "    fs.readFile(path, 'utf8', (err, raw) => {",
      '      if (err) return reject(err);',
      '      resolve(JSON.parse(raw));',
      '    });',
      '  });',
      '}',
    ],
    selectionLine: 4,
    variableName: 'raw',
    expectedLine: 5,
  },
  {
    name: 'statement inside a reduce callback in a return is logged after the statement',
    fileExtension: '.js',
    lines: [
      'function indexById(items) {',
      '  return items.reduce((acc, item) => {',
      '    acc[item.id] = item;',
      '    return acc;',
      '  }, {});',
      '}',
    ],
    selectionLine: 2,
    variableName: 'item',
    expectedLine: 3,
  },
  {
    name: 'inner return of a curried middleware is logged before the inner return',
    fileExtension: '.js',
    lines: [
      'const loadPost = (Model) => {',
      '  return async (req, res, next) => {',
      '    const post = await Model.findById(req.params.id);',
      '    if (!post) {',
      '      return res.status(404).json({ id: req.params.id });',
      '    }',
      '    req.post = post;',
      '    next();',
      '  };',
      '};',
    ],
    selectionLine: 4,
    variableName: 'req.params.id',
    expectedLine: 4,
  },
  {
    name: 'for-of header inside a filter callback in a return is logged before the loop',
    fileExtension: '.js',
    lines: [
      'function visible(items, blocked) {',
      '  return items.filter((item) => {',
      '    for (const tag of item.tags) {',
      '      if (blocked.has(tag)) return false;',
      '    }',
      '    return true;',
      '  });',
      '}',
    ],
    selectionLine: 2,
    variableName: 'item.tags',
    expectedLine: 2,
  },
  {
    name: 'method-call object in a return whose callback spans lines is logged before the return',
    fileExtension: '.js',
    lines: [
      'function ids(items) {',
      '  return items.map((item) => {',
      '    return item.id;',
      '  });',
      '}',
    ],
    selectionLine: 1,
    variableName: 'items',
    expectedLine: 1,
  },
  {
    name: 'return inside a forEach callback is logged before that return',
    fileExtension: '.js',
    lines: [
      'function f(items) {',
      '  items.forEach((item) => {',
      '    return item.id;',
      '  });',
      '}',
    ],
    selectionLine: 2,
    variableName: 'item.id',
    expectedLine: 2,
  },
  {
    name: 'unary const is logged after the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function Toggle({ open }) {',
      '  const next = !open;',
      '  return next;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'next',
    expectedLine: 2,
  },
];
