import { InsertionEngineCase } from './types';

// The call-assignment checker accepts `new X(…)` and `<T>call(…)` initializers,
// but the call line helper only recognises plain (awaited / `as` / parenthesized)
// CallExpressions, so it falls back to `selectionLine + 1`: inside the argument
// list for multi-line statements.
export const callLikeInitializerCases: InsertionEngineCase[] = [
  {
    name: 'multi-line new QueryClient declaration in a .tsx module is logged after the statement',
    fileExtension: '.tsx',
    lines: [
      "import { QueryClient, QueryClientProvider } from '@tanstack/react-query';",
      '',
      'const queryClient = new QueryClient({',
      '  defaultOptions: {',
      '    queries: { staleTime: 60_000 },',
      '  },',
      '});',
      '',
      'export function Providers({ children }: { children: React.ReactNode }) {',
      '  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;',
      '}',
    ],
    selectionLine: 2,
    variableName: 'queryClient',
    expectedLine: 7,
  },
  {
    name: 'multi-line new IntersectionObserver declaration is logged after the statement',
    fileExtension: '.tsx',
    lines: [
      'export function useInView(ref: React.RefObject<Element>) {',
      '  const [visible, setVisible] = useState(false);',
      '  useEffect(() => {',
      '    const observer = new IntersectionObserver(',
      '      ([entry]) => {',
      '        setVisible(entry.isIntersecting);',
      '      },',
      '      { threshold: 0.1 },',
      '    );',
      '    if (ref.current) observer.observe(ref.current);',
      '    return () => observer.disconnect();',
      '  }, [ref]);',
      '  return visible;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'observer',
    expectedLine: 9,
  },
  {
    name: 'new ResizeObserver declaration with a block callback is logged after the statement, not inside the callback',
    fileExtension: '.tsx',
    lines: [
      'export function useSize(ref: React.RefObject<HTMLElement>) {',
      '  useEffect(() => {',
      '    const ro = new ResizeObserver((entries) => {',
      '      setSize(entries[0].contentRect);',
      '    });',
      '    ro.observe(ref.current!);',
      '    return () => ro.disconnect();',
      '  }, [ref]);',
      '}',
    ],
    selectionLine: 2,
    variableName: 'ro',
    expectedLine: 5,
  },
  {
    name: 'multi-line generic new expression declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'const subject = new BehaviorSubject<State>(',
      '  initialState,',
      ');',
      'subject.next(next);',
    ],
    selectionLine: 0,
    variableName: 'subject',
    expectedLine: 3,
  },
  {
    name: 'angle-bracket type assertion on a multi-line call declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'function decode(token: string) {',
      '  const payload = <JwtPayload>jwt.verify(',
      '    token,',
      '    process.env.JWT_SECRET!,',
      '  );',
      '  return payload.sub;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'payload',
    expectedLine: 5,
  },
  {
    name: 'angle-bracket assertion on a multi-line awaited destructured call is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'async function list(url: string) {',
      '  const { data } = <AxiosResponse<User[]>>await axios.get(',
      '    url,',
      '  );',
      '  return data;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'data',
    expectedLine: 4,
  },
  {
    name: 'as-cast multi-line call declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'const settings = JSON.parse(',
      '  raw,',
      ') as Settings;',
      'use(settings);',
    ],
    selectionLine: 0,
    variableName: 'settings',
    expectedLine: 3,
  },
  {
    name: 'single-line new expression declaration is logged after the statement',
    fileExtension: '.ts',
    lines: ['const client = new QueryClient();', 'use(client);'],
    selectionLine: 0,
    variableName: 'client',
    expectedLine: 1,
  },
];
