import { InsertionEngineCase } from './types';

// Bindings of a multi-line destructuring declaration that no declaration checker
// recognises (a defaulted key, a `yield` or `import()` initializer) fall to
// WanderingExpression, which logs BEFORE the multi-line statement: a TDZ
// ReferenceError.
export const destructuringBindingCases: InsertionEngineCase[] = [
  {
    name: 'defaulted key in a multi-line props destructuring is logged after the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function Button(props: ButtonProps) {',
      '  const {',
      '    children,',
      "    variant = 'primary',",
      '    size,',
      '    ...rest',
      '  } = props;',
      '  return <button className={buttonVariants({ variant, size })} {...rest}>{children}</button>;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'variant',
    expectedLine: 7,
  },
  {
    name: 'defaulted key in a multi-line this.props destructuring is logged after the declaration',
    fileExtension: '.tsx',
    lines: [
      'class Chart extends React.Component<ChartProps> {',
      '  render() {',
      '    const {',
      '      width = 600,',
      '      height,',
      '    } = this.props;',
      '    return <svg width={width} height={height} />;',
      '  }',
      '}',
    ],
    selectionLine: 3,
    variableName: 'width',
    expectedLine: 6,
  },
  {
    name: 'defaulted key in a multi-line process.env destructuring is logged after the declaration',
    fileExtension: '.cjs',
    lines: [
      'const {',
      '  PORT = 3000,',
      "  NODE_ENV = 'development',",
      '  DATABASE_URL,',
      '} = process.env;',
      'app.listen(PORT);',
    ],
    selectionLine: 1,
    variableName: 'PORT',
    expectedLine: 5,
  },
  {
    name: 'destructured binding of a multi-line yield call is logged after the declaration',
    fileExtension: '.js',
    lines: [
      'function* fetchUserSaga(action) {',
      '  const { data } = yield call(',
      '    api.fetchUser,',
      '    action.payload.id,',
      '  );',
      '  yield put(userLoaded(data));',
      '}',
    ],
    selectionLine: 1,
    variableName: 'data',
    expectedLine: 5,
  },
  {
    name: 'destructured binding of a multi-line dynamic import is logged after the declaration',
    fileExtension: '.mjs',
    lines: [
      'const {',
      '  readFile,',
      '  writeFile,',
      "} = await import('node:fs/promises');",
      'await writeFile(out, await readFile(src));',
    ],
    selectionLine: 1,
    variableName: 'readFile',
    expectedLine: 4,
  },
  {
    name: 'non-defaulted key in a multi-line destructuring with defaults is logged after the declaration',
    fileExtension: '.cjs',
    lines: [
      'const {',
      '  PORT = 3000,',
      '  DATABASE_URL,',
      '} = process.env;',
      'app.listen(PORT);',
    ],
    selectionLine: 2,
    variableName: 'DATABASE_URL',
    expectedLine: 4,
  },
  {
    name: 'identifier bound to a multi-line yield call is logged after the declaration',
    fileExtension: '.js',
    lines: [
      'function* saga(action) {',
      '  const response = yield call(',
      '    api.fetchUser,',
      '    action.id,',
      '  );',
      '  yield put(response);',
      '}',
    ],
    selectionLine: 1,
    variableName: 'response',
    expectedLine: 5,
  },
  {
    name: 'destructured binding of a multi-line require is logged after the declaration',
    fileExtension: '.js',
    lines: [
      'const {',
      '  readFile,',
      '  writeFile,',
      "} = require('fs/promises');",
      'use(readFile);',
    ],
    selectionLine: 1,
    variableName: 'readFile',
    expectedLine: 4,
  },
  {
    name: 'destructured binding of a single-line call is logged after the declaration',
    fileExtension: '.ts',
    lines: ['const { data, error } = useSWR(key, fetcher);', 'use(data);'],
    selectionLine: 0,
    variableName: 'data',
    expectedLine: 1,
  },
];
