import { InsertionEngineCase } from './types';

// A declaration inside a callback passed to an OUTER call declaration. The call
// line helper takes the first covering declaration in pre-order: a destructured
// outer declaration matches without binding the selected name, and a same-named
// outer identifier shadows the inner one, so the log lands after the outer
// statement, where the inner binding is out of scope.
export const innerDeclarationInCallbackCases: InsertionEngineCase[] = [
  {
    name: 'const inside a useState lazy initializer is not swallowed by the destructured outer declaration',
    fileExtension: '.tsx',
    lines: [
      'export function useLocalStorage<T>(key: string, initialValue: T) {',
      '  const [storedValue, setStoredValue] = useState<T>(() => {',
      '    try {',
      '      const item = window.localStorage.getItem(key);',
      '      return item ? (JSON.parse(item) as T) : initialValue;',
      '    } catch (error) {',
      '      console.warn(error);',
      '      return initialValue;',
      '    }',
      '  });',
      '  const setValue = (value: T | ((val: T) => T)) => {',
      '    const valueToStore = value instanceof Function ? value(storedValue) : value;',
      '    setStoredValue(valueToStore);',
      '    window.localStorage.setItem(key, JSON.stringify(valueToStore));',
      '  };',
      '  return [storedValue, setValue] as const;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'item',
    expectedLine: 4,
  },
  {
    name: 'const inside a useQuery queryFn is not swallowed by the destructured outer declaration',
    fileExtension: '.tsx',
    lines: [
      'export function useProjectTodos(projectId?: string) {',
      '  const { data: todos, isPending } = useQuery({',
      "    queryKey: ['todos', projectId],",
      '    queryFn: async () => {',
      '      const res = await fetch(`/api/projects/${projectId}/todos`);',
      "      if (!res.ok) throw new Error('Failed to load todos');",
      '      return res.json();',
      '    },',
      '    enabled: !!projectId,',
      '  });',
      '  return { todos, isPending };',
      '}',
    ],
    selectionLine: 4,
    variableName: 'res',
    expectedLine: 5,
  },
  {
    name: 'const inside a useSWR fetcher is not swallowed by the destructured outer declaration',
    fileExtension: '.tsx',
    lines: [
      'export function useUser(id: string) {',
      '  const { data, error } = useSWR(`/api/users/${id}`, async (url: string) => {',
      '    const res = await fetch(url);',
      '    const json = await res.json();',
      '    return json;',
      '  });',
      '  return { user: data, error };',
      '}',
    ],
    selectionLine: 2,
    variableName: 'res',
    expectedLine: 3,
  },
  {
    name: 'const inside a NextAuth callback is not swallowed by the exported destructured declaration',
    fileExtension: '.ts',
    lines: [
      "import NextAuth from 'next-auth';",
      '',
      'export const { handlers, signIn, signOut, auth } = NextAuth({',
      '  providers: [GitHub],',
      '  callbacks: {',
      '    async session({ session, token }) {',
      '      const dbUser = await getUserById(token.sub);',
      '      session.user.role = dbUser.role;',
      '      return session;',
      '    },',
      '  },',
      '});',
    ],
    selectionLine: 6,
    variableName: 'dbUser',
    expectedLine: 7,
  },
  {
    name: 'inner const shadowing the outer call declaration name is logged after the inner declaration',
    fileExtension: '.ts',
    lines: [
      'const result = await db.transaction(async (tx) => {',
      '  const result = await tx.insert(orders).values(order).returning();',
      '  await tx.insert(audit).values({ orderId: result[0].id });',
      '  return result;',
      '});',
    ],
    selectionLine: 1,
    variableName: 'result',
    expectedLine: 2,
  },
  {
    name: 'const inside a callback of an identifier-bound call declaration is logged after the inner declaration',
    fileExtension: '.tsx',
    lines: [
      'export function useProjectTodos(projectId) {',
      '  const query = useQuery({',
      '    queryFn: async () => {',
      '      const res = await fetch(url);',
      '      return res.json();',
      '    },',
      '  });',
      '  return query;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'res',
    expectedLine: 4,
  },
  {
    name: 'renamed binding of a multi-line destructured call declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'const { data: todos, isPending } = useQuery({',
      "  queryKey: ['todos'],",
      '});',
      'use(todos);',
    ],
    selectionLine: 0,
    variableName: 'todos',
    expectedLine: 3,
  },
  // Guards from the second review: a same-named declaration opening on the
  // outer statement's first line must not steal an outer-name selection.
  {
    name: 'outer declaration wins over a same-named inner declaration opening on its first line',
    fileExtension: '.ts',
    lines: [
      'const result = await db.transaction(async (tx) => { const result = await tx.insert(row);',
      '  return result;',
      '});',
      'use(result);',
    ],
    selectionLine: 0,
    variableName: 'result',
    expectedLine: 3,
  },
  {
    name: 'outer destructured declaration wins over a same-named inner declaration in its initializer on the same line',
    fileExtension: '.tsx',
    lines: [
      'const [items, setItems] = useState(() => { const items = load();',
      '  return items;',
      '});',
    ],
    selectionLine: 0,
    variableName: 'items',
    expectedLine: 3,
  },
];
