import { InsertionEngineCase } from './types';

// Selecting the object of a method call (`obj` in `obj.method()`). The log is
// placed relative to the statement enclosing the call: before an if/while
// condition (top of the body for an else-if), before a throw, before a
// multi-line statement the call is only a piece of, after it otherwise.
export const methodCallObjectCases: InsertionEngineCase[] = [
  {
    name: 'method-call object in a compound if condition is logged before the if statement',
    fileExtension: '.ts',
    lines: [
      'export function middleware(request: NextRequest) {',
      "  const token = request.cookies.get('token')?.value;",
      "  if (!token && request.nextUrl.pathname.startsWith('/dashboard')) {",
      "    return NextResponse.redirect(new URL('/login', request.url));",
      '  }',
      '  return NextResponse.next();',
      '}',
    ],
    selectionLine: 2,
    variableName: 'request.nextUrl.pathname',
    expectedLine: 2,
  },
  {
    name: 'method-call object in a braceless single-line if is logged before the if statement',
    fileExtension: '.ts',
    lines: [
      'export function middleware(request: NextRequest) {',
      '  const { pathname } = request.nextUrl;',
      "  if (pathname.startsWith('/admin')) {",
      "    return NextResponse.redirect(new URL('/login', request.url));",
      '  }',
      "  if (!allowedOrigins.includes(request.headers.get('origin') ?? '')) return new Response(null, { status: 403 });",
      '  return NextResponse.next();',
      '}',
    ],
    selectionLine: 5,
    variableName: 'allowedOrigins',
    expectedLine: 5,
  },
  {
    name: 'method-call object in a negated if guard is logged before the if statement',
    fileExtension: '.tsx',
    lines: [
      'export function AdminGate({ user, children }: Props) {',
      "  if (!user.roles.includes('admin')) {",
      '    return <Forbidden />;',
      '  }',
      '  return <>{children}</>;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'user.roles',
    expectedLine: 1,
  },
  {
    name: 'method-call object in a multi-line if condition is logged before the if statement',
    fileExtension: '.ts',
    lines: [
      'export class AuthGuard {',
      '  canActivate(user: User): boolean {',
      '    if (',
      '      this.authService.isLoggedIn() &&',
      '      user.active',
      '    ) {',
      '      return true;',
      '    }',
      '    return false;',
      '  }',
      '}',
    ],
    selectionLine: 3,
    variableName: 'this.authService',
    expectedLine: 2,
  },
  {
    name: 'method-call object in a while condition is logged before the loop',
    fileExtension: '.ts',
    lines: [
      'async function drain(queue: Queue<Job>) {',
      '  while (queue.hasPending()) {',
      '    await queue.processNext();',
      '  }',
      '}',
    ],
    selectionLine: 1,
    variableName: 'queue',
    expectedLine: 1,
  },
  {
    name: 'method-call object inside a parenthesized JSX const is logged before the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function Title({ user }: Props) {',
      '  const heading = (',
      '    <h1>{user.name.toUpperCase()}</h1>',
      '  );',
      '  return heading;',
      '}',
    ],
    selectionLine: 2,
    variableName: 'user.name',
    expectedLine: 1,
  },
  {
    name: 'map root inside a parenthesized JSX const is logged before the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function Nav({ links }: Props) {',
      '  const menu = (',
      '    <ul>',
      '      {links.map((link) => (',
      '        <li key={link.href}>{link.label}</li>',
      '      ))}',
      '    </ul>',
      '  );',
      '  return <nav>{menu}</nav>;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'links',
    expectedLine: 1,
  },
  {
    name: 'method-call object inside a multi-line call argument is logged before the statement',
    fileExtension: '.tsx',
    lines: [
      'export function Combobox({ options, value }: Props) {',
      '  const [selected, setSelected] = useState<Option | null>(null);',
      '  useEffect(() => {',
      '    setSelected(',
      '      options.find((o) => o.value === value) ?? null,',
      '    );',
      '  }, [options, value]);',
      '  return <Listbox value={selected} />;',
      '}',
    ],
    selectionLine: 4,
    variableName: 'options',
    expectedLine: 3,
  },
  {
    name: 'root of a multi-line method chain declaration is logged before the declaration',
    fileExtension: '.tsx',
    lines: [
      'export function ActiveUsers({ users }: Props) {',
      '  const activeUsers = users',
      '    .filter((u) => u.active)',
      '    .sort((a, b) => a.name.localeCompare(b.name));',
      '  return <UserList users={activeUsers} />;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'users',
    expectedLine: 1,
  },
  {
    name: 'method-call object inside a single-line throw is logged before the throw',
    fileExtension: '.js',
    lines: [
      'function assertConfig(config) {',
      '  const missing = REQUIRED.filter((key) => !config[key]);',
      '  if (missing.length > 0) {',
      "    throw new ConfigError(missing.join(', '));",
      '  }',
      '}',
    ],
    selectionLine: 3,
    variableName: 'missing',
    expectedLine: 3,
  },
  {
    name: 'method-call object in an else-if condition is logged at the top of the else-if body',
    fileExtension: '.ts',
    lines: [
      'function route(user: User | null) {',
      '  if (!user) {',
      "    return redirect('/login');",
      "  } else if (user.roles.includes('admin')) {",
      "    return redirect('/admin');",
      '  }',
      "  return redirect('/home');",
      '}',
    ],
    selectionLine: 3,
    variableName: 'user.roles',
    expectedLine: 4,
  },
  {
    name: 'method-call object in a single-line declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'function f(name) {',
      '  const upper = name.toUpperCase();',
      '  return upper;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'name',
    expectedLine: 2,
  },
  {
    name: 'member method-call object in a single-line declaration is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'function f(user) {',
      "  const isAdmin = user.roles.includes('admin');",
      '  return isAdmin;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'user.roles',
    expectedLine: 2,
  },
];
