import { InsertionEngineCase } from './types';

// Reassignments (no `const`/`let`) whose right-hand side spans several lines.
// Like declarations, they are logged after the whole statement so the log
// prints the assigned value, for identifier and member targets alike, at
// module top level and inside function bodies.
export const multiLineReassignmentCases: InsertionEngineCase[] = [
  {
    name: 'top-level member reassigned to a multi-line object is logged after the statement',
    fileExtension: '.ts',
    lines: ['this.state = {', '  ready: true,', '};', 'next();'],
    selectionLine: 0,
    variableName: 'this.state',
    expectedLine: 3,
  },
  {
    name: 'top-level member reassigned to a multi-line awaited call is logged after the statement',
    fileExtension: '.ts',
    lines: ['obj.data = await load(', '  id,', ');', 'next();'],
    selectionLine: 0,
    variableName: 'obj.data',
    expectedLine: 3,
  },
  {
    name: 'top-level member reassigned to a multi-line ternary is logged after the statement',
    fileExtension: '.ts',
    lines: ['obj.mode = dark', "  ? 'dark'", "  : 'light';", 'next();'],
    selectionLine: 0,
    variableName: 'obj.mode',
    expectedLine: 3,
  },
  {
    name: 'top-level member reassigned to a multi-line template literal is logged after the statement',
    fileExtension: '.ts',
    lines: ['obj.text = `a', '${b}`;', 'next();'],
    selectionLine: 0,
    variableName: 'obj.text',
    expectedLine: 2,
  },
  {
    name: 'identifier reassigned to a multi-line object is logged after the statement',
    fileExtension: '.ts',
    lines: ['let state;', 'state = {', '  ready: true,', '};', 'next();'],
    selectionLine: 1,
    variableName: 'state',
    expectedLine: 4,
  },
  {
    name: 'identifier reassigned to a multi-line object inside a function is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'function reset() {',
      '  let state;',
      '  state = {',
      '    ready: true,',
      '  };',
      '  next(state);',
      '}',
    ],
    selectionLine: 2,
    variableName: 'state',
    expectedLine: 5,
  },
  {
    name: 'identifier reassigned to a multi-line awaited call is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'async function sync(id) {',
      '  let data;',
      '  data = await load(',
      '    id,',
      '  );',
      '  next(data);',
      '}',
    ],
    selectionLine: 2,
    variableName: 'data',
    expectedLine: 5,
  },
  {
    name: 'identifier reassigned to a multi-line ternary is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'let mode;',
      'mode = dark',
      "  ? 'dark'",
      "  : 'light';",
      'next();',
    ],
    selectionLine: 1,
    variableName: 'mode',
    expectedLine: 4,
  },
  // Compound and logical operators (`??=`, `||=`) are anchored the same way.
  {
    name: 'member logically assigned (??=) to a multi-line new expression inside a function is logged after the statement',
    fileExtension: '.js',
    lines: [
      'function getClient() {',
      '  globalThis.prisma ??= new PrismaClient({',
      "    log: ['query'],",
      '  });',
      '  return globalThis.prisma;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'globalThis.prisma',
    expectedLine: 4,
  },
  {
    name: 'identifier logically assigned (||=) to a multi-line awaited call is logged after the statement',
    fileExtension: '.js',
    lines: [
      'let connection;',
      'async function getConnection() {',
      '  connection ||= await mysql.createConnection({',
      '    uri: process.env.DATABASE_URL,',
      '  });',
      '  return connection;',
      '}',
    ],
    selectionLine: 2,
    variableName: 'connection',
    expectedLine: 5,
  },
  {
    name: 'identifier logically assigned (||=) to a multi-line call is logged after the statement',
    fileExtension: '.js',
    lines: [
      'let client;',
      'client ||= createClient({',
      '  url,',
      '});',
      'use(client);',
    ],
    selectionLine: 1,
    variableName: 'client',
    expectedLine: 4,
  },
  // Guards: single-line and in-function shapes that already resolved correctly.
  {
    name: 'member logically assigned (??=) on a single line is logged after the statement',
    fileExtension: '.js',
    lines: [
      'function getClient() {',
      '  globalThis.prisma ??= new PrismaClient();',
      '  return globalThis.prisma;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'globalThis.prisma',
    expectedLine: 2,
  },
  {
    name: 'member reassigned to a multi-line awaited call inside a function is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'async function sync(obj, id) {',
      '  obj.data = await load(',
      '    id,',
      '  );',
      '  next();',
      '}',
    ],
    selectionLine: 1,
    variableName: 'obj.data',
    expectedLine: 4,
  },
  {
    name: 'member reassigned to a multi-line object inside a method is logged after the statement',
    fileExtension: '.ts',
    lines: [
      'class Store {',
      '  reset() {',
      '    this.state = {',
      '      ready: true,',
      '    };',
      '    next();',
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'this.state',
    expectedLine: 5,
  },
  // Guard from the second review: an inner same-target assignment opening on
  // the outer statement's first line must not steal the selection.
  {
    name: 'outer reassignment wins over a same-target assignment in its callback on the same line',
    fileExtension: '.js',
    lines: ['x = f(() => { x = 1;', '  more();', '});'],
    selectionLine: 0,
    variableName: 'x',
    expectedLine: 3,
  },
];
