import { InsertionEngineCase } from './types';

// Intended placements the engine already honours. They guard the fixes above
// against regressions and document behaviour that must NOT be "fixed".
export const placementConventionCases: InsertionEngineCase[] = [
  {
    name: 'if condition member is logged before the if statement',
    fileExtension: '.ts',
    lines: ['if (user.isAdmin && user.active) {', '  grant();', '}'],
    selectionLine: 0,
    variableName: 'user.isAdmin',
    expectedLine: 0,
  },
  {
    name: 'multi-line if condition member is logged before the if statement',
    fileExtension: '.ts',
    lines: ['if (', '  user &&', '  user.active', ') {', '  go();', '}'],
    selectionLine: 2,
    variableName: 'user.active',
    expectedLine: 0,
  },
  {
    name: 'while condition member is logged before the loop',
    fileExtension: '.ts',
    lines: ['while (queue.length) {', '  step();', '}'],
    selectionLine: 0,
    variableName: 'queue.length',
    expectedLine: 0,
  },
  {
    name: 'selection inside a multi-line call statement is logged before it',
    fileExtension: '.ts',
    lines: ['logger.info(', "  'started',", '  payload,', ');', 'next();'],
    selectionLine: 2,
    variableName: 'payload',
    expectedLine: 0,
  },
  {
    name: 'selection inside a single-line call statement is logged after it',
    fileExtension: '.ts',
    lines: ['log(`x ${v}`);', 'next();'],
    selectionLine: 0,
    variableName: 'v',
    expectedLine: 1,
  },
  {
    name: 'returned member is logged before the return',
    fileExtension: '.ts',
    lines: ['function getName(person) {', '  return person.name;', '}'],
    selectionLine: 1,
    variableName: 'person.name',
    expectedLine: 1,
  },
  {
    name: 'single-line member assignment is logged after the statement',
    fileExtension: '.ts',
    lines: ['class A {', '  constructor(x) {', '    this.x = x;', '  }', '}'],
    selectionLine: 2,
    variableName: 'this.x',
    expectedLine: 3,
  },
  {
    name: 'single-line identifier reassignment is logged after the statement',
    fileExtension: '.ts',
    lines: ['let value;', 'value = compute();', 'use(value);'],
    selectionLine: 1,
    variableName: 'value',
    expectedLine: 2,
  },
  {
    name: 'member reassigned to a multi-line array is logged after the statement',
    fileExtension: '.ts',
    lines: ['obj.items = [', '  1,', '  2,', '];', 'next();'],
    selectionLine: 0,
    variableName: 'obj.items',
    expectedLine: 4,
  },
  {
    name: 'declared multi-line object is logged after the declaration',
    fileExtension: '.ts',
    lines: [
      'const config = {',
      '  a: 1,',
      '  nested: {',
      '    b: 2,',
      '  },',
      '};',
      'use(config);',
    ],
    selectionLine: 0,
    variableName: 'config',
    expectedLine: 6,
  },
  {
    name: 'deep key in a declared object logs its full path after the declaration',
    fileExtension: '.ts',
    lines: [
      'const config = {',
      '  a: 1,',
      '  nested: {',
      '    b: 2,',
      '  },',
      '};',
      'use(config);',
    ],
    selectionLine: 3,
    variableName: 'b',
    expectedLine: 6,
    expectedDeepObjectPath: 'config.nested.b',
  },
  {
    name: 'single-line optional-chained call result is logged after the declaration',
    fileExtension: '.ts',
    lines: ['const v = obj?.method?.(arg);', 'use(v);'],
    selectionLine: 0,
    variableName: 'v',
    expectedLine: 1,
  },
  {
    name: 'multi-line awaited call result is logged after the declaration',
    fileExtension: '.ts',
    lines: [
      'const result = await fetchData(',
      '  url,',
      '  options,',
      ');',
      'use(result);',
    ],
    selectionLine: 0,
    variableName: 'result',
    expectedLine: 4,
  },
  {
    name: 'variable declared inside a catch handler is logged after its declaration',
    fileExtension: '.ts',
    lines: [
      'try {',
      '  run();',
      '} catch (err) {',
      '  const code = err.code;',
      '}',
    ],
    selectionLine: 3,
    variableName: 'code',
    expectedLine: 4,
  },
  {
    name: 'multi-line arrow parameter is logged at the top of the body',
    fileExtension: '.ts',
    lines: ['const fn = (', '  a,', '  b,', ') => {', '  return a + b;', '};'],
    selectionLine: 1,
    variableName: 'a',
    expectedLine: 4,
  },
  {
    name: 'parameter of an arrow with an expression body goes through the transformer',
    fileExtension: '.ts',
    lines: ['const f = (a) =>', '  a + 1;', 'use(f);'],
    selectionLine: 0,
    variableName: 'a',
    expectedLine: 1,
    expectsTransformation: true,
  },
];
