import { InsertionEngineCase } from './types';

// Script extraction for .vue/.svelte/.astro files fails before the engine runs:
// the `<script[^>]*>` tag regex stops at a `>` inside an attribute, matches
// `<ScriptEditor>`/`<script-list>` and self-closing tags, and Astro frontmatter
// is parsed without allowing a top-level `return`.
export const sfcScriptExtractionCases: InsertionEngineCase[] = [
  {
    name: 'Astro frontmatter with a top-level return is parsed and the declaration logged after it',
    fileExtension: '.astro',
    lines: [
      '---',
      "import Layout from '../layouts/Layout.astro';",
      "import { getEntry } from 'astro:content';",
      '',
      'const { slug } = Astro.params;',
      "const post = await getEntry('blog', slug!);",
      'if (!post) {',
      "  return Astro.redirect('/404');",
      '}',
      'const { Content } = await post.render();',
      '---',
      '',
      '<Layout title={post.data.title}><Content /></Layout>',
    ],
    selectionLine: 4,
    variableName: 'slug',
    expectedLine: 5,
    knownBroken: true,
  },
  {
    name: 'Vue script setup whose generic attribute contains > is parsed',
    fileExtension: '.vue',
    lines: [
      '<script setup lang="ts" generic="T extends Record<string, unknown>">',
      'const props = defineProps<{ rows: T[]; sortKey: keyof T }>();',
      'const sorted = computed(() => [...props.rows]);',
      '</script>',
      '',
      '<template>',
      '  <table><tr v-for="row in sorted"><td>{{ row }}</td></tr></table>',
      '</template>',
    ],
    selectionLine: 1,
    variableName: 'props',
    expectedLine: 2,
    knownBroken: true,
  },
  {
    name: 'Svelte script whose generics attribute contains > is parsed',
    fileExtension: '.svelte',
    lines: [
      '<script lang="ts" generics="T extends Record<string, unknown>">',
      '  let { rows }: { rows: T[] } = $props();',
      '  let sorted = $derived([...rows]);',
      '</script>',
    ],
    selectionLine: 1,
    variableName: 'rows',
    expectedLine: 2,
    knownBroken: true,
  },
  {
    name: 'Astro script with an arrow inside define:vars is parsed',
    fileExtension: '.astro',
    lines: [
      '---',
      'const { items } = Astro.props;',
      '---',
      '<ul id="list"></ul>',
      '<script define:vars={{ ids: items.map((item) => item.id) }}>',
      "  const list = document.getElementById('list');",
      "  list.dataset.ids = ids.join(',');",
      '</script>',
    ],
    selectionLine: 5,
    variableName: 'list',
    expectedLine: 6,
    knownBroken: true,
  },
  {
    name: 'Vue template with a ScriptEditor component before the script is parsed',
    fileExtension: '.vue',
    lines: [
      '<template>',
      '  <div class="panel">',
      '    <ScriptEditor v-model="code" :language="language" />',
      '  </div>',
      '</template>',
      '',
      '<script setup lang="ts">',
      "const code = ref('');",
      "const language = ref<'js' | 'ts'>('ts');",
      '</script>',
    ],
    selectionLine: 7,
    variableName: 'code',
    expectedLine: 8,
    knownBroken: true,
  },
  {
    name: 'Vue template with a kebab-case script-list component before the script is parsed',
    fileExtension: '.vue',
    lines: [
      '<template>',
      '  <script-list :items="scripts" @run="onRun" />',
      '</template>',
      '',
      '<script>',
      'export default {',
      '  methods: {',
      '    onRun(script) {',
      '      this.running = script.id;',
      '    },',
      '  },',
      '};',
      '</script>',
    ],
    selectionLine: 7,
    variableName: 'script',
    expectedLine: 8,
    knownBroken: true,
  },
  {
    name: 'Astro self-closing JSON-LD script tag does not swallow the next script',
    fileExtension: '.astro',
    lines: [
      '---',
      'const { title, url } = Astro.props;',
      "const schema = { '@context': 'https://schema.org', '@type': 'WebPage', name: title, url };",
      '---',
      '',
      '<head>',
      '  <title>{title}</title>',
      '  <script type="application/ld+json" set:html={JSON.stringify(schema)} />',
      '</head>',
      '<body>',
      '  <nav id="menu"></nav>',
      '  <script>',
      "    const menu = document.getElementById('menu');",
      "    menu?.classList.add('ready');",
      '  </script>',
      '</body>',
    ],
    selectionLine: 12,
    variableName: 'menu',
    expectedLine: 13,
    knownBroken: true,
  },
  {
    name: 'Vue script setup ref declaration is logged after the declaration',
    fileExtension: '.vue',
    lines: ['<script setup lang="ts">', "const code = ref('');", '</script>'],
    selectionLine: 1,
    variableName: 'code',
    expectedLine: 2,
  },
];
