import { InsertionEngineCase } from './types';

// WanderingExpression climbs to the nearest statement node. `switch`,
// `export default`, `import x = require()`, `export =` and labels are not
// statement boundaries, so the climb overshoots (often to line 0, before the
// declarations it reads). A single-line `throw` gets the "after" rule, which is
// dead code.
export const statementBoundaryCases: InsertionEngineCase[] = [
  {
    name: 'switch discriminant in a TSX reducer function is logged before the switch',
    fileExtension: '.tsx',
    lines: [
      'function reducer(state: State, action: Action): State {',
      '  switch (action.type) {',
      "    case 'added': {",
      '      return [...state, { id: action.id, text: action.text }];',
      '    }',
      "    case 'deleted':",
      '      return state.filter((t) => t.id !== action.id);',
      '    default:',
      "      throw Error('Unknown action: ' + action.type);",
      '  }',
      '}',
    ],
    selectionLine: 1,
    variableName: 'action.type',
    expectedLine: 1,
  },
  {
    name: 'switch discriminant on a component prop is logged before the switch',
    fileExtension: '.tsx',
    lines: [
      'export function StatusBadge({ status }: { status: Status }) {',
      '  switch (status) {',
      "    case 'active':",
      '      return <Badge color="green">Active</Badge>;',
      "    case 'paused':",
      '      return <Badge color="yellow">Paused</Badge>;',
      '    default:',
      '      return null;',
      '  }',
      '}',
    ],
    selectionLine: 1,
    variableName: 'status',
    expectedLine: 1,
  },
  {
    name: 'switch discriminant in an arrow reducer is logged before the switch',
    fileExtension: '.ts',
    lines: [
      'const cartReducer = (state: CartState, action: CartAction): CartState => {',
      '  switch (action.type) {',
      "    case 'add':",
      '      return { ...state, items: [...state.items, action.item] };',
      '    default:',
      '      return state;',
      '  }',
      '};',
    ],
    selectionLine: 1,
    variableName: 'action.type',
    expectedLine: 1,
  },
  {
    name: 'switch discriminant in a JS reducer function is logged before the switch',
    fileExtension: '.js',
    lines: [
      'function reducer(state, action) {',
      '  switch (action.type) {',
      "    case 'add':",
      '      return [...state, action.payload];',
      '    default:',
      '      return state;',
      '  }',
      '}',
    ],
    selectionLine: 1,
    variableName: 'action.type',
    expectedLine: 1,
  },
  {
    name: 'switch discriminant inside an Express handler is logged before the switch',
    fileExtension: '.js',
    lines: [
      "app.post('/webhook', (req, res) => {",
      '  const event = req.body;',
      '  switch (event.type) {',
      "    case 'payment_intent.succeeded':",
      '      handlePayment(event.data.object);',
      '      break;',
      '  }',
      '  res.sendStatus(200);',
      '});',
    ],
    selectionLine: 2,
    variableName: 'event.type',
    expectedLine: 2,
  },
  {
    name: 'export default connect()() is logged after the export',
    fileExtension: '.tsx',
    lines: [
      "'use client';",
      '',
      "import { connect } from 'react-redux';",
      '',
      'const mapStateToProps = (state: RootState) => ({ todos: state.todos });',
      '',
      'function TodoList({ todos }: Props) {',
      '  return <ul>{todos.length}</ul>;',
      '}',
      '',
      'export default connect(mapStateToProps)(TodoList);',
    ],
    selectionLine: 10,
    variableName: 'mapStateToProps',
    expectedLine: 11,
  },
  {
    name: 'export default memo() in a use client file is logged after the export',
    fileExtension: '.tsx',
    lines: [
      "'use client';",
      '',
      'function ProductCard({ product }: Props) {',
      '  return <article>{product.name}</article>;',
      '}',
      '',
      'export default memo(ProductCard);',
    ],
    selectionLine: 6,
    variableName: 'ProductCard',
    expectedLine: 7,
  },
  {
    name: 'export default identifier in an .mjs module is logged after the export',
    fileExtension: '.mjs',
    lines: [
      "import express from 'express';",
      'const router = express.Router();',
      "router.get('/', list);",
      'export default router;',
    ],
    selectionLine: 3,
    variableName: 'router',
    expectedLine: 4,
  },
  {
    name: 'TS import-equals declaration is logged after the import',
    fileExtension: '.ts',
    lines: ["import fs = require('fs');", 'use(fs);'],
    selectionLine: 0,
    variableName: 'fs',
    expectedLine: 1,
  },
  {
    name: 'TS export assignment is logged after the statement',
    fileExtension: '.ts',
    lines: [
      "const config = loadConfig('app');",
      '',
      'export = createApp(config);',
    ],
    selectionLine: 2,
    variableName: 'config',
    expectedLine: 3,
  },
  {
    name: 'loop header under a label on its own line is logged before the label',
    fileExtension: '.js',
    lines: [
      'function scan(matrix) {',
      '  search:',
      '  for (const row of matrix) {',
      '    for (const cell of row) {',
      '      if (cell < 0) break search;',
      '    }',
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'matrix',
    expectedLine: 1,
  },
  {
    name: 'member inside a single-line throw is logged before the throw',
    fileExtension: '.js',
    lines: [
      'async function getJson(url) {',
      '  const response = await fetch(url, {',
      "    headers: { Accept: 'application/json' },",
      '  });',
      '  if (!response.ok) {',
      '    throw new Error(`HTTP ${response.status}`);',
      '  }',
      '  return response.json();',
      '}',
    ],
    selectionLine: 5,
    variableName: 'response.status',
    expectedLine: 5,
  },
  {
    name: 'rethrown catch parameter is logged before the throw',
    fileExtension: '.js',
    lines: [
      'async function run() {',
      '  try {',
      '    await job();',
      '  } catch (err) {',
      '    logger.error(err);',
      '    throw err;',
      '  }',
      '}',
    ],
    selectionLine: 5,
    variableName: 'err',
    expectedLine: 5,
  },
  {
    name: 'selection inside a multi-line throw is logged before it',
    fileExtension: '.js',
    lines: [
      'function fail(msg) {',
      '  throw new Error(',
      '    msg,',
      '  );',
      '}',
    ],
    selectionLine: 2,
    variableName: 'msg',
    expectedLine: 1,
  },
  {
    name: 'for-of header member is logged before the loop',
    fileExtension: '.js',
    lines: ['for (const tag of item.tags) {', '  use(tag);', '}'],
    selectionLine: 0,
    variableName: 'item.tags',
    expectedLine: 0,
  },
  {
    name: 'single-statement export default file is logged after the export',
    fileExtension: '.ts',
    lines: ['export default memo(ProductCard);'],
    selectionLine: 0,
    variableName: 'ProductCard',
    expectedLine: 1,
  },
  {
    name: 'const inside a switch case block is logged after the declaration',
    fileExtension: '.ts',
    lines: [
      'switch (type) {',
      "  case 'a': {",
      '    const v = get();',
      '    break;',
      '  }',
      '}',
    ],
    selectionLine: 2,
    variableName: 'v',
    expectedLine: 3,
  },
];
