import { InsertionEngineCase } from './types';

// needTransformation rewrites an expression-bodied arrow that does not own the
// selection: its name-matching also hits member property names and object keys
// (`state.auth.user`, `{ status: v }`), and it walks into nested object methods.
// The log then lands in the wrong scope (TDZ or ReferenceError).
export const transformerFalsePositiveCases: InsertionEngineCase[] = [
  {
    name: 'useSelector result named like a selected member property is not transformed',
    fileExtension: '.tsx',
    lines: [
      'export function Header() {',
      '  const user = useSelector((state: RootState) => state.auth.user);',
      '  const isOpen = useCartStore((s) => s.isOpen);',
      "  const names = users.map((u) => u.name).join(', ');",
      '  return <Nav user={user} open={isOpen} />;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'user',
    expectedLine: 2,
  },
  {
    name: 'JSX prop variable that is also an object key in a same-line arrow is not transformed',
    fileExtension: '.tsx',
    lines: [
      'export function Filters({ filters, setFilters, status }: Props) {',
      '  return <Select value={status} onChange={(v) => setFilters({ ...filters, status: v })} />;',
      '}',
    ],
    selectionLine: 1,
    variableName: 'status',
    expectedLine: 1,
  },
  {
    name: 'Vue computed assigned to a const named like the getter property is not transformed',
    fileExtension: '.vue',
    lines: [
      '<script setup lang="ts">',
      'const props = defineProps<{ isOpen: boolean }>();',
      'const isOpen = computed(() => props.isOpen);',
      'watch(isOpen, (open) => {',
      "  document.body.style.overflow = open ? 'hidden' : '';",
      '});',
      '</script>',
    ],
    selectionLine: 2,
    variableName: 'isOpen',
    expectedLine: 3,
  },
  {
    name: 'Astro filter result named like the predicate property is not transformed',
    fileExtension: '.astro',
    lines: [
      '---',
      "const posts = await getCollection('blog');",
      'const featured = posts.filter((post) => post.data.featured);',
      '---',
      '',
      '<FeaturedList posts={featured} />',
    ],
    selectionLine: 2,
    variableName: 'featured',
    expectedLine: 3,
  },
  {
    name: 'watch callback parameter named like the getter property is logged in the callback, not the getter',
    fileExtension: '.vue',
    lines: [
      '<script setup lang="ts">',
      'const route = useRoute();',
      'watch(() => route.params.id, async (id) => {',
      '  await load(id);',
      '});',
      '</script>',
    ],
    selectionLine: 2,
    variableName: 'id',
    expectedLine: 3,
  },
  {
    name: 'destructured watch callback parameter is logged in the callback, not the getter',
    fileExtension: '.vue',
    lines: [
      '<script setup lang="ts">',
      'watch([() => props.page, search], ([page, query]) => {',
      '  fetchResults(page, query);',
      '});',
      '</script>',
    ],
    selectionLine: 1,
    variableName: 'page',
    expectedLine: 2,
  },
  {
    name: 'Alpine object-method parameter does not transform the outer expression-bodied arrow',
    fileExtension: '.html',
    lines: [
      '<div x-data="dropdown"></div>',
      '<script>',
      "  document.addEventListener('alpine:init', () => {",
      "    Alpine.data('dropdown', () => ({",
      '      open: false,',
      '      toggle() {',
      '        this.open = !this.open;',
      '      },',
      '      select(option) {',
      '        this.selected = option;',
      '        this.open = false;',
      '      },',
      '    }));',
      '  });',
      '</script>',
    ],
    selectionLine: 8,
    variableName: 'option',
    expectedLine: 9,
  },
  {
    name: 'const inside an Alpine object method does not transform the outer expression-bodied arrow',
    fileExtension: '.html',
    lines: [
      '<div x-data="list"></div>',
      '<script>',
      "  document.addEventListener('alpine:init', () => {",
      "    Alpine.data('list', () => ({",
      '      items: [],',
      '      async load() {',
      "        const res = await fetch('/api/items');",
      '        this.items = await res.json();',
      '      },',
      '    }));',
      '  });',
      '</script>',
    ],
    selectionLine: 6,
    variableName: 'res',
    expectedLine: 7,
  },
  {
    name: 'parameter of a same-line expression-bodied selector goes through the transformer',
    fileExtension: '.tsx',
    lines: [
      'const user = useSelector((state) => state.auth.user);',
      'render(user);',
    ],
    selectionLine: 0,
    variableName: 'state',
    expectedLine: 1,
    expectsTransformation: true,
  },
  {
    name: 'block callback parameter of watch is logged at the top of the body',
    fileExtension: '.ts',
    lines: ['watch(source, async (id) => {', '  await load(id);', '});'],
    selectionLine: 0,
    variableName: 'id',
    expectedLine: 1,
  },
  {
    name: 'member inside an expression-bodied map callback in a JSX return goes through the transformer',
    fileExtension: '.tsx',
    lines: [
      'export function List({ items }) {',
      '  return (',
      '    <ul>',
      '      {items.map((item) => (',
      '        <li key={item.id}>{item.label}</li>',
      '      ))}',
      '    </ul>',
      '  );',
      '}',
    ],
    selectionLine: 4,
    variableName: 'item.label',
    expectedLine: 1,
    expectsTransformation: true,
  },
];
