export default {
  name: 'Vue SFC - binary expression in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ result }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { count: 10 };',
    '  },',
    '  methods: {',
    '    calculate() {',
    '      const sum = this.count + 5;',
    '      return sum;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'sum',
};
