export default {
  name: 'Vue SFC - template string in computed',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ greeting }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { name: "World" };',
    '  },',
    '  computed: {',
    '    greeting() {',
    '      const message = `Hello, ${this.name}!`;',
    '      return message;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'message',
};
