export default {
  name: 'Vue SFC - within if condition in method',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ status }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { isAuthenticated: false, status: "" };',
    '  },',
    '  methods: {',
    '    checkAuth() {',
    '      if (this.isAuthenticated) {',
    '        this.status = "Logged in";',
    '      }',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'this.isAuthenticated',
  expected: true,
};
