export default {
  name: 'Vue SFC - ternary expression in computed property',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div :class="statusClass">{{ statusText }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { isActive: true, isError: false };',
    '  },',
    '  computed: {',
    '    statusClass() {',
    '      const className = this.isError ? "error" : this.isActive ? "active" : "inactive";',
    '      return className;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'className',
};
