export default {
  name: 'Vue SFC - raw property access in computed',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ fullName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { user: { profile: { name: "Alice" } } };',
    '  },',
    '  computed: {',
    '    fullName() {',
    '      return this.user.profile.name;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'this.user.profile.name',
  expectedLine: 12,
};
