export default {
  name: 'Vue SFC - within return statement in computed',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ fullName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { firstName: "John", lastName: "Doe" };',
    '  },',
    '  computed: {',
    '    fullName() {',
    '      return `${this.firstName} ${this.lastName}`;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'this.firstName',
  expected: 11,
};
