export default {
  name: 'Vue SFC - binary expression in computed',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ total }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { price: 100, tax: 0.2 };',
    '  },',
    '  computed: {',
    '    total() {',
    '      const result = this.price * (1 + this.tax);',
    '      return result;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'result',
  expectedLine: 12,
};
