export default {
  name: 'Vue SFC - within return statement in computed property',
  fileExtension: '.vue',
  lines: [
    '<template>',
    '  <div>{{ displayName }}</div>',
    '</template>',
    '',
    '<script>',
    'export default {',
    '  data() {',
    '    return { user: { firstName: "John", lastName: "Doe" } };',
    '  },',
    '  computed: {',
    '    displayName() {',
    '      return `${this.user.firstName} ${this.user.lastName}`;',
    '    }',
    '  }',
    '};',
    '</script>',
  ],
  selectionLine: 11,
  variableName: 'this.user.firstName',
};
